App Insights Construction and availability as well as login UI enhancements
kpqdap/qchat pull request #162
Opened 2024-03-25 00:53 UTC by kpqdap

The below implements additional app insights fixes as well and the variables at build time.
Currently the Create Tenant on failed login does not work as expected and must be debugged.

2024-03-25 04:32 UTC, rshokqdap commented
Transcribe and App Insights are working after passing the arguments during the docker build.

https://dis-qgcdg.atlassian.net/browse/QGGPT-376

2024-03-25 05:05 UTC, QDAP-Fred requested changes

2024-03-25 05:39 UTC, QDAP-Fred requested changes

2024-03-25 05:39 UTC, QDAP-Fred commented on src/next.config.js
> +    styledComponents: true,
this can be removed since we aren't using styled-components

2024-03-25 05:39 UTC, QDAP-Fred commented on src/features/auth/auth-api.ts
> +  debug: process.env.NODE_ENV === "development" ? true : false,
can be simplified to `debug: process.env.NODE_ENV === "development",`

2024-03-25 05:39 UTC, QDAP-Fred commented on azure-pipelines.yml
> +              azureSubscription: "$(Dev_Service_Connection)"
make sure `Dev_Service_Connection` is added in the variable groups

2024-03-25 05:39 UTC, QDAP-Fred commented on src/features/auth/sign-in.ts
> +export enum ErrorType {
I would recommend something like this to be more explicit (name and type wise):
```
export enum SignInErrorType {
  NotAuthorised = "notAuthorised",
  SignInFailed = "signInFailed",
}
type SignInSuccess = {
  success: true
}
type SignInError = {
  success: false
  errorCode: SignInErrorType
}
export type SignInResponse = SignInSuccess | SignInError
```

that way it wouldn't be possible to return a response such as 
```
{
  success: true,
  errorCode: ErrorType.NotAuthorised,
}
```

2024-03-25 05:39 UTC, QDAP-Fred commented on src/features/auth/auth-api.ts
> +        if (signInCallbackResponse.success === true) {
could be simplified:
`if (signInCallbackResponse.success) ...`

2024-03-26 00:35 UTC, rshokqdap approved these changes

2024-03-26 00:36 UTC, merged